### ISSUE TITLE
Tarea del módulo 1.2

### ISSUE THREAD

**Issue by eocares** [SistemasTecTlaxiaco/EbertOcares#2]
Esta en 2 archivos jpg.
![Captura2](https://user-images.githubusercontent.com/26308417/211716981-348d8f69-3b3a-4735-994a-d47299e15b1e.PNG)
![Captura1](https://user-images.githubusercontent.com/26308417/211716986-b87b8bf6-0f56-417c-8c92-8ec13f1921fa.PNG)

**Comment by josealfredo79** [comment]
Muy bien...por el trabajo realizado en Git en su computadora local
